### ISSUE TITLE
example in Readme does not work

### ISSUE THREAD

**Issue by davidbenque** [TheJokersThief/daft-scraper#18]
My scripts are returning empty dicts instead of listing results since upgrading to 1.3.0. I tried reproducing the example in the Readme as my code didn't diverge too much from it, and it returns: 

```python
     20 listings = api.search(options)
     21 
---> 22 print(len(listings))
     23 for listing in listings:
     24     print(getattr(listing, 'title'))

TypeError: object of type 'generator' has no len()
```

If I remove that print statement nothing gets returned and the `listings` generator seems to be empty?

**Comment by TheJokersThief** [comment]
Hey @davidbenque, it turns out those criteria no longer return any properties 😛 It looks like the max price limit I set as an example is too low for swords.

I've updated the readme to remove the print `len` line and increase the max price but I'll add a CI test soon I think to make sure that the readme example works as it's come up once or twice now when I've made updates - sorry about that!

You're probably already familiar but if you want to retain the non-generator functionality, you can simply cast it to a list and it'll work like before:

```python
listings = api.search(options)

listings = list(listings)
for listing in listings:
	print(listing.title)
```

Hope that answers your issue! :) Let me know if not or if there's anything else I can help with

**Comment by davidbenque** [comment]
Thank you for the quick response and guidance. I was able to fix my scripts by following your new example. The initial reason for upgrading from 1.0.2 was that I was struggling to query houses for sale (rather than rent). But now that works too! 

Many thanks for providing this tool!
